### ISSUE TITLE
missing svg icon

### ISSUE THREAD

**Issue by 19emtuck** [cozy-labs/cozy-ghost#12]
it seems a svg file is missing in ghost application 
"api/applications/blog.svg"

no way to find that svg resource

/usr/local/cozy/apps/blog# find . -name "*.svg"
./client/vendor/assets/fonts/glyphicons-halflings-regular.svg
./server/ghost/package/core/client/assets/fonts/icons.svg
./server/ghost/package/content/themes/casper/assets/fonts/casper-icons.svg
./server/ghost/core/client/assets/fonts/icons.svg
./server/ghost/content/themes/casper/assets/fonts/casper-icons.svg

![image](https://cloud.githubusercontent.com/assets/956861/13744924/6c4314fc-e9eb-11e5-8388-38222bbb89a9.png)

**Comment by frankrousseau** [comment]
This icon is located in the cozy-home folder. It's weird that it's not installed. Whatever thank you for reporting. We'll have a look at it.

**Comment by 19emtuck** [comment]
to give you all informations, it's because I cannot install _blog_ through the web interface
and did it by command line (it seems building sqlite is very slow and timeout occure on webinterface)

cd /usr/local/cozy/apps/
sudo git clone https://github.com/cozy-labs/cozy-ghost blog
cd blog
npm install
cd ..
chown -R cozy-blog.cozy-blog ./blog

after that, the application seems ok

I also copied it from the demo website (https://cozy.io/fr/images/apps/blog.svg)
in :
/usr/local/cozy/apps/home/build/client/public/img/apps/blog.svg
/usr/local/cozy/apps/home/client/app/assets/img/apps/blog.svg

now wget 127.0.0.0/api/applications/blog.svg
returns me the right svg content

bug chrome still don't want to read it correctly. That's strange

**Comment by clochix** [comment]
Hi @19emtuck,

Have you any error when you try to install Blog from the Cozy marketplace?

If you want to install an application by hand, you must use `cozy-monitor`:

```
cozy-monitor install -r https://github.com/cozy-labs/cozy-ghost blog
```

Cloning the repository isn't enough, as the application won't be registered in the list of installed applications, and this may lead to weirds behaviors.

**Comment by 19emtuck** [comment]
Got this error while installing it by web interface :

socket hang up: Error: socket hang up at createHangUpError (_http_client.js:200:15) at Socket.socketOnEnd (_http_client.js:292:23) at emitNone (events.js:72:20) at Socket.emit (events.js:166:7) at endReadableNT (_stream_readable.js:905:12) at nextTickCallbackWith2Args (node.js:442:9) at process._tickCallback (node.js:356:17)

Tell me if there's a better log somwhere else

**Comment by clochix** [comment]
Thanks for the error log. Looks like the application is taking too long to install. Are you on a server slow or with low memory, like a π ?

Did you manage to install Ghost by using `cozy-monitor install` ? If it takes too long, you can add `--timeout false` to disable timeout.

**Comment by 19emtuck** [comment]
~# cozy-monitor install -r https://github.com/cozy-labs/cozy-ghost blog --timeout false
info - Install started for blog...

never finished after 3 hours, got errors insde npm-debug.log, strangely I didn't get error during sqlite module compilation while bare installing it with "sudo npm install" and blog was working (the only issue was about svg)

1623 silly linkStuff tar@2.2.1 has /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules as its parent node_modules
1624 verbose linkBins tar@2.2.1
1625 verbose linkMans tar@2.2.1
1626 verbose rebuildBundles tar@2.2.1
1627 verbose rebuildBundles [ 'block-stream', 'fstream', 'inherits' ]
1628 info install tar@2.2.1
1629 info postinstall tar@2.2.1
1630 verbose rebuild bundle /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
1631 info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
1632 info preinstall tar-pack@2.0.0
1633 info linkStuff tar-pack@2.0.0
1634 silly linkStuff tar-pack@2.0.0 has /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules as its parent node_modules
1635 verbose linkBins tar-pack@2.0.0
1636 verbose linkMans tar-pack@2.0.0
1637 verbose rebuildBundles tar-pack@2.0.0
1638 verbose rebuildBundles [ 'debug',
1638 verbose rebuildBundles   'fstream',
1638 verbose rebuildBundles   'fstream-ignore',
1638 verbose rebuildBundles   'graceful-fs',
1638 verbose rebuildBundles   'once',
1638 verbose rebuildBundles   'readable-stream',
1638 verbose rebuildBundles   'rimraf',
1638 verbose rebuildBundles   'tar',
1638 verbose rebuildBundles   'uid-number' ]
1639 info install tar-pack@2.0.0
1640 info postinstall tar-pack@2.0.0
1641 info install node-pre-gyp@0.6.14
1642 info postinstall node-pre-gyp@0.6.14
1643 info install sqlite3@3.1.1
1644 verbose unsafe-perm in lifecycle true
1645 info sqlite3@3.1.1 Failed to exec install script
1646 verbose unlock done using /usr/local/cozy/apps/blog/.npm/_locks/sqlite3-483e758002d2e975.lock for /usr/local/cozy/apps/blog/node_modules/sqlite3
1647 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
1647 verbose stack Exit status 1
1647 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
1647 verbose stack     at emitTwo (events.js:87:13)
1647 verbose stack     at EventEmitter.emit (events.js:172:7)
1647 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1647 verbose stack     at emitTwo (events.js:87:13)
1647 verbose stack     at ChildProcess.emit (events.js:172:7)
1647 verbose stack     at maybeClose (internal/child_process.js:827:16)
1647 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1648 verbose pkgid sqlite3@3.1.1
1649 verbose cwd /usr/local/cozy/apps/blog
1650 error Linux 3.4.61+
1651 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "--production" "--loglevel" "info" "install"
1652 error node v4.4.0
1653 error npm  v2.14.20
1654 error code ELIFECYCLE
1655 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
1655 error Exit status 1
1656 error Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
1656 error This is most likely a problem with the sqlite3 package,
1656 error not with npm itself.
1656 error Tell the author that this fails on your system:
1656 error     node-pre-gyp install --fallback-to-build
1656 error You can get information on how to open an issue for this project with:
1656 error     npm bugs sqlite3
1656 error Or if that isn't available, you can get their info via:
1656 error
1656 error     npm owner ls sqlite3
1656 error There is likely additional logging output above.
1657 verbose exit [ 1, true ]
1658 verbose unbuild node_modules/sqlite3

**Comment by clochix** [comment]
:-S
Ghost uses sqlite3, and the sqlite3 driver for Node seems to have problems compiling. Maybe could you find more logs inside the node_modules/sqlite3 folder.

**Comment by 19emtuck** [comment]
sorry for the lag, didn't get anything about sqlite log.
Tell me where to find that log or how to generate it.

**Comment by clochix** [comment]
Coud you try a clean re-install of sqlite3?

```
cd /usr/local/cozy/apps/blog
rm -rf node_modules/sqlite3
npm install --production --loglevel info --unsafe-perm true --user cozy-blog
```

**Comment by 19emtuck** [comment]
compilation achieve correctly, the application start also, but icon is still broken.

below partial console log output (certainly uninteresting)

---

npm info postinstall npmlog@1.2.1
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rc
npm info preinstall rc@1.1.2
npm info linkStuff rc@1.1.2
npm info install rc@1.1.2
npm info postinstall rc@1.1.2
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/request
npm info preinstall request@2.64.0
npm info linkStuff request@2.64.0
npm info install request@2.64.0
npm info postinstall request@2.64.0
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rimraf
npm info preinstall rimraf@2.4.3
npm info linkStuff rimraf@2.4.3
npm info install rimraf@2.4.3
npm info postinstall rimraf@2.4.3
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/semver
npm info preinstall semver@5.0.3
npm info linkStuff semver@5.0.3
npm info install semver@5.0.3
npm info postinstall semver@5.0.3
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar
npm info preinstall tar@2.2.1
npm info linkStuff tar@2.2.1
npm info install tar@2.2.1
npm info postinstall tar@2.2.1
npm info build /usr/local/cozy/apps/blog/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
npm info preinstall tar-pack@2.0.0
npm info linkStuff tar-pack@2.0.0
npm info install tar-pack@2.0.0
npm info postinstall tar-pack@2.0.0
npm info install node-pre-gyp@0.6.14
npm info postinstall node-pre-gyp@0.6.14
npm info install sqlite3@3.1.1

> sqlite3@3.1.1 install /usr/local/cozy/apps/blog/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.14
node-pre-gyp info using node@4.4.0 | linux | arm
node-pre-gyp info check checked for "/usr/local/cozy/apps/blog/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v46-linux-arm.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v46-linux-arm.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v46-linux-arm.tar.gz (falling back to source compile with node-gyp)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.4.0 | linux | arm
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.4.0 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/cozy/apps/blog/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/4.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/4.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/cozy/apps/blog/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.4.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/usr/local/cozy/apps/blog/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o

---

../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton_)':
../src/database.cc:227:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton_)':
../src/database.cc:505:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton_)':
../src/database.cc:605:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton_)':
../src/statement.cc:118:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:322:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:370:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:438:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:504:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:601:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton_)':
../src/macros.h:125:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:724:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY /usr/local/cozy/apps/blog/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/usr/local/cozy/apps/blog/node_modules/sqlite3/build'
gyp info ok
node-pre-gyp info ok
npm info postinstall sqlite3@3.1.1
npm info build /usr/local/cozy/apps/blog
npm info linkStuff cozy-blog@1.0.0
npm info install cozy-blog@1.0.0
npm info postinstall cozy-blog@1.0.0
sqlite3@3.1.1 node_modules/sqlite3
└── nan@2.1.0
npm info ok

**Comment by clochix** [comment]
So it looks like that the application is successfully installed, but still appears as broken because the list of installed applications has not been updated. Could you try to restart it: `cozy-monitor restart ghost`, then check its status in `cozy-monitor status`?

**Comment by 19emtuck** [comment]
pi@truck:/usr/local/cozy/apps/blog> sudo cozy-monitor restart blog
info - Restart blog...
info - blog successfully restarted.
pi@truck:/usr/local/cozy/apps/blog> sudo cozy-monitor status
mta: up
couch: up
controller: up
data-system: up
home: up
proxy: up
emails: stopped
owm: stopped
polybios: stopped
quickmarks: stopped
zero-feeds: stopped
blog: up
calendar: up
contacts: up
databrowser: up
files: up
hastebin: up
notes: up
photos: up
sync: up
tasky: up
term: up

**Comment by frankrousseau** [comment]
I messed up with commits of this repository yesterday.

**Comment by clochix** [comment]
Thanks @19emtuck. So Ghost now seems installed. Have you any other problem with it?

**Comment by 19emtuck** [comment]
icon is still broken
frankrousseau says "I messed up with commits of this repository yesterday". Shall I retry ?

**Comment by 19emtuck** [comment]
frankrousseau says "I messed up with commits of this repository yesterday". Shall I retry ?
